package com.p3l.gah_mobile.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00668A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC3E8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2C)
val md_theme_light_secondary = Color(0xFF815600)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDDB1)
val md_theme_light_onSecondaryContainer = Color(0xFF291800)
val md_theme_light_tertiary = Color(0xFF00668A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDCE3E9)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787D)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFF7AD0FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00668A)
val md_theme_light_outlineVariant = Color(0xFFC0C7CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7AD0FF)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004C68)
val md_theme_dark_onPrimaryContainer = Color(0xFFC3E8FF)
val md_theme_dark_secondary = Color(0xFFFEBA4B)
val md_theme_dark_onSecondary = Color(0xFF442B00)
val md_theme_dark_secondaryContainer = Color(0xFF614000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDB1)
val md_theme_dark_tertiary = Color(0xFF7AD0FF)
val md_theme_dark_onTertiary = Color(0xFF003549)
val md_theme_dark_tertiaryContainer = Color(0xFF004C68)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3E8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF00668A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7AD0FF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF336A86)
val iconColor = Color(0xFFB69B61)
val green = Color(0xFFD3EDDA)
val greenIcon = Color(0xFF63BB67)
val orange = Color(0xFFEBE0DC)
val orangeIcon = Color(0xFFE8A87C)

val slate400 = Color(0xFF94A3B8)
val slate500 = Color(0xFF6B7280)
val slate800 = Color(0xFF1E293B)

val warning =  Color(0xFFFDEDD3)
val warningText = Color(0xFFC3841D)

val success = Color(0xFFD0F4E0)
val successText = Color(0xFF12A150)

val successTable = Color(0xFF009688)

val primary = Color(0xFFD6E1E7)
val primaryText = Color(0xFF326A85)

val secondary = Color(0xFFE4D4F4)
val secondaryText = Color(0xFF7828C8)

val danger = Color(0xFFFDCFDF)
val dangerText = Color(0xFFF31260)